export const Products = [
  {
    title: "Training shoes",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis, qui?",
    price: 49.99,
    rating: Math.floor(Math.random() * (5 - 1 + 1) + 1),
    peopleRated: "524",
    isAddedToCart: false,
    isInWishlist: false,
  },
  {
    title: "Sneakers",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis, qui?",
    price: 29.99,
    rating: Math.floor(Math.random() * (5 - 1 + 1) + 1),
    peopleRated: "691",
    isAddedToCart: false,
    isInWishlist: true,
  },
  {
    title: "Running shoes",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis, qui?",
    price: 39.99,
    rating: Math.floor(Math.random() * (5 - 1 + 1) + 1),
    peopleRated: "831",
    isAddedToCart: true,
    isInWishlist: false,
  },
  {
    title: "Training shoes",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis, qui?",
    price: 49.99,
    rating: Math.floor(Math.random() * (5 - 1 + 1) + 1),
    peopleRated: "478",
    isAddedToCart: false,
    isInWishlist: true,
  },
  {
    title: "Sneakers",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis, qui?",
    price: 29.99,
    rating: Math.floor(Math.random() * (5 - 1 + 1) + 1),
    peopleRated: "434",
    isAddedToCart: true,
    isInWishlist: false,
  },
  {
    title: "Running shoes",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis, qui?",
    price: 39.99,
    rating: Math.floor(Math.random() * (5 - 1 + 1) + 1),
    peopleRated: "762",
    isAddedToCart: true,
    isInWishlist: false,
  },
  {
    title: "Training shoes",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis, qui?",
    price: 49.99,
    rating: Math.floor(Math.random() * (5 - 1 + 1) + 1),
    peopleRated: "494",
    isAddedToCart: false,
    isInWishlist: true,
  },
  {
    title: "Sneakers",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis, qui?",
    price: 29.99,
    rating: Math.floor(Math.random() * (5 - 1 + 1) + 1),
    peopleRated: "488",
    isAddedToCart: true,
    isInWishlist: true,
  },
  {
    title: "Running shoes",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis, qui?",
    price: 39.99,
    rating: Math.floor(Math.random() * (5 - 1 + 1) + 1),
    peopleRated: "960",
    isAddedToCart: false,
    isInWishlist: false,
  },
];